import { useRef, useState } from 'react';
import { ChevronRight, Download, Upload, MapPin, LockKeyhole, UserRound, Compass, Image, Palette } from 'lucide-react';
import type { AppState } from '../lib/model';
import { getCityProgress, getProfileTrips, getProfileVisits } from '../lib/model';
import { cities } from '../data/cities';
import type { CityId } from '../data/cities';
import { exportBackup } from '../lib/storage';
export function ProfileScreen({ state, onAccount, onLocation, onMapTheme, onCity, onImport, onGallery, onToast }: { state: AppState; onAccount: () => void; onLocation: () => void; onMapTheme: () => void; onCity: (cityId: CityId) => void; onImport: (file: File) => void; onGallery: () => void; onToast: (message: string) => void }) {
  const input = useRef<HTMLInputElement>(null);
  const [busy, setBusy] = useState(false);
  const download = async () => { setBusy(true); try { const blob = await exportBackup(state); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `vesluma-backup-${new Date().toISOString().slice(0,10)}.json`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 2000); onToast('已导出记录与照片备份'); } catch (e) { onToast(e instanceof Error ? e.message : '导出失败，请重试。'); } finally { setBusy(false); } };
  return <div className="profile-screen scroll-screen"><header className="profile-heading"><h1>我的足迹</h1></header><div className="profile-identity"><div className="avatar">{state.profile.name.slice(0,1)}</div><div><h2>{state.profile.name}</h2><p>{getProfileTrips(state).length} 次旅程 · {getProfileVisits(state).length} 次到访</p></div><button className="icon-button" aria-label="切换本地体验账号" onClick={onAccount}><UserRound size={20} /></button></div><div className="screen-padding"><h2 className="section-title">一点一点，展开世界</h2>{cities.map(city => { const progress = getCityProgress(state,city.id); return <button key={city.id} className="profile-city" onClick={() => onCity(city.id)}><img src={`/images/${city.id === 'nanjing' ? 'nanjing' : 'xian'}.png`} alt="城市概念影像" /><div><b>{city.name}</b><p>已展开 {progress.unlocked} / {progress.total} 个试验区 · 到访 {progress.visited} 个地标</p><div className="progress-track"><span style={{width:`${progress.ratio*100}%`}} /></div></div><ChevronRight size={17} color="#9aac9e" /></button>; })}<h2 className="section-title">关于这一程</h2><button className="setting-row" onClick={onGallery}><Image size={18}/><span>我的相册</span><small>{getProfileVisits(state).length} 张</small><ChevronRight size={15}/></button><button className="setting-row" onClick={onMapTheme}><Palette size={18}/><span>地图显示主题</span><small>{state.mapTheme === 'treasure' ? '藏宝图' : '纸感地图'}</small><ChevronRight size={15}/></button><button className="setting-row" onClick={onLocation}><Compass size={18}/><span>位置与体验方式</span><small>{state.locationMode === 'demo' ? '演示位置' : '设备定位'}</small><ChevronRight size={15}/></button><button className="setting-row" disabled={busy} onClick={download}><Download size={18}/><span>{busy ? '正在整理照片…' : '导出完整备份'}</span><small>记录与照片</small><ChevronRight size={15}/></button><button className="setting-row" onClick={() => input.current?.click()}><Upload size={18}/><span>从备份恢复</span><small>手动迁移设备</small><ChevronRight size={15}/></button><input className="sr-only" ref={input} type="file" accept="application/json,.json" aria-label="选择旅行备份" onChange={e => { if(e.target.files?.[0]) onImport(e.target.files[0]); e.target.value=''; }} /><div className="notice-box"><LockKeyhole size={14} style={{verticalAlign:'middle',marginRight:6}}/>照片默认私密，公开由你主动选择。<br/><MapPin size={14} style={{verticalAlign:'middle',marginRight:6}}/>本地体验版尚未连接云空间。小队与公开相册仅在本设备的体验账号之间演示。</div><div className="brand-footer"><b>Vesluma</b>展开一座城，留下这一程。<small>Uncover the city. Keep the memories.</small></div></div></div>;
}
